apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: fnfcentral-ssl
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: joseph@dualvs.com
    privateKeySecretRef:
      name: fnfcentral-ssl-secret
    http01: {}
