apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fnfcentral-ssl-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: joseph@dualvs.com
    privateKeySecretRef:
      name: fnfcentral-ssl-production-key
    solvers:
      - http01:
          ingress:
            class: nginx
