apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fnfcentral-ssl-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: joseph@dualvs.com
    privateKeySecretRef:
      name: fnfcentral-ssl-secret
    solvers:
      - http01:
          ingress:
            class: nginx
