apiVersion: v1
kind: Service
metadata:
  name: fnfcentral-kratos
spec:
  selector:
    app: fnfcentral-kratos
  ports:
    - name: fnfcentral-kratos-http
      protocol: TCP
      port: 80
      targetPort: 4433
