apiVersion: apps/v1
kind: Deployment
metadata:
  name: fnfcentral-kratos
spec:
  replicas: {{.Values.kratos.scale}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: fnfcentral-kratos
  template:
    metadata:
      labels:
        app: fnfcentral-kratos
    spec:
      containers:
        - name: kratos
          image: {{.Values.kratos.image}}:{{.Chart.Version}}
          command: ["kratos"]
          args: ["serve", "--watch-courier", "--config", "/home/ory/kratos.yml"]
          ports:
            - containerPort: 4433
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: fnfcentral-secret-data
                  key: Kratos-DSN
            - name: SERVE_PUBLIC_CORS_ALLOWED_ORIGINS
              value: https://{{.Values.fnfcentral.domain}}
            - name: SELFSERVICE_DEFAULT_BROWSER_RETURN_URL
              value: https://{{.Values.fnfcentral.domain}}/dashboard
            - name: SELFSERVICE_FLOWS_VERIFICATION_UI_URL
              value: https://{{.Values.fnfcentral.domain}}/dashboard
            - name: SELFSERVICE_FLOWS_RECOVERY_UI_URL
              value: https://{{.Values.fnfcentral.domain}}/recover
            - name: SELFSERVICE_FLOWS_SETTINGS_UI_URL
              value: https://{{.Values.fnfcentral.domain}}/recover
            - name: SELFSERVICE_WHITELISTED_RETURN_URLS
              value: https://{{.Values.fnfcentral.domain}}
            - name: SERVE_PUBLIC_BASE_URL
              value: https://{{.Values.kratos.domain}}
            - name: COURIER_SMTP_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: fnfcentral-secret-data
                  key: Kratos-COURIER_SMTP_CONNECTION_URI
            - name: COURIER_SMTP_FROM_ADDRESS
              value: {{.Values.kratos.email.name}}@{{.Values.kratos.email.domain}}
            - name: SESSION_COOKIE_DOMAIN
              value: {{.Values.fnfcentral.domain}}
            - name: SECRETS_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: fnfcentral-kratos-secret-data
                  key: SECRETS_DEFAULT
            - name: SECRETS_CIPHER
              valueFrom:
                secretKeyRef:
                  name: fnfcentral-kratos-secret-data
                  key: SECRETS_CIPHER
            - name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: fnfcentral-kratos-secret-data
                  key: SECRETS_COOKIE
