apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: fnfcentral-migration
          image: {{.Values.fnfcentral.image}}:{{.Values.fnfcentral.tag}}
          command: ["npx"]
          args: ["prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              value: postgresql://{{.Values.fnfcentral.database.username}}:{{.Values.fnfcentral.database.password}}@{{.Values.fnfcentral.database.domain}}:{{.Values.fnfcentral.database.port}}/{{.Values.fnfcentral.database.loginDatabase}}?sslmode=allow&schema=api
        - name: fnfcentral-kratos-migration
          image: {{.Values.kratos.image}}:{{.Values.kratos.tag}}
          command: ["kratos"]
          args: ["migrate", "--config", "/home/ory/kratos.yml", "sql", "-e", "--yes"]
          env:
            - name: DSN
              value: postgresql://{{.Values.kratos.database.username}}:{{.Values.kratos.database.password}}@{{.Values.kratos.database.domain}}:{{.Values.kratos.database.port}}/{{.Values.kratos.database.loginDatabase}}?sslmode=allow
