apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: fnfcentral-migration
          image: {{.Values.fnfcentral.image}}:{{.Values.fnfcentral.tag}}
          command: ["npx"]
          args: ["prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fnfcentral-secret-data
                  key: FNFCentral-DATABASE_URL
        - name: fnfcentral-kratos-migration
          image: {{.Values.kratos.image}}:{{.Values.kratos.tag}}
          command: ["kratos"]
          args: ["migrate", "--config", "/home/ory/kratos.yml", "sql", "-e", "--yes"]
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: fnfcentral-secret-data
                  key: Kratos-DSN
