{{-  $fnfcentralDatabaseURL := printf "postgresql://%s:%s@%s:%s/%s?sslmode=allow&schema=api" .Values.fnfcentral.database.username .Values.fnfcentral.database.password .Values.fnfcentral.database.domain .Values.fnfcentral.database.port .Values.fnfcentral.database.loginDatabase -}}
{{-  $kratosDSN := printf "postgresql://%s:%s@%s:%s/%s?sslmode=allow" .Values.kratos.database.username .Values.kratos.database.password .Values.kratos.database.domain .Values.kratos.database.port .Values.kratos.database.loginDatabase -}}
{{-  $kratosSMTP := printf "smtps://%s:%s@%s:%s/?skip_ssl_verify=true&legacy_ssl=true" .Values.kratos.smtps.username .Values.kratos.smtps.password .Values.kratos.smtps.domain .Values.kratos.smtps.port -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fnfcentral-secret-data
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  FNFCentral-DATABASE_URL: {{ $fnfcentralDatabaseURL | b64enc | quote }}
  FNFCentral-LDAP_BIND_PASS: {{ .Values.fnfcentral.ldap.bind.pass | b64enc | quote }}
  FNFCentral-JWT_SECRET: {{ .Values.fnfcentral.jwt.secret | b64enc | quote }}
  Kratos-DSN: {{ $kratosDSN | b64enc | quote }}
  Kratos-COURIER_SMTP_CONNECTION_URI: {{ $kratosSMTP | b64enc | quote }}
