apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fnfcentral-kratos-secret-data
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  SECRETS_DEFAULT: {{randAlphaNum 24 | nospace | b64enc | quote}}
  SECRETS_CIPHER: {{randAlphaNum 24 | nospace | b64enc | quote}}
  SECRETS_COOKIE: {{randAlphaNum 24 | nospace | b64enc | quote}}
