apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fnfcentral-secret-data
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  password: MWYyZDFlMmU2N2Rm
  FNFCentral-DATABASE_URL: postgresql://{{.Values.fnfcentral.database.username}}:{{.Values.fnfcentral.database.password}}@{{.Values.fnfcentral.database.domain}}:{{.Values.fnfcentral.database.port}}/{{.Values.fnfcentral.database.loginDatabase}}?sslmode=allow&schema=api
  FNFCentral-LDAP_BIND_PASS: {{.Values.fnfcentral.ldap.bind.pass}}
  FNFCentral-JWT_SECRET: {{.Values.fnfcentral.jwt.secret}}
  Kratos-DSN: postgresql://{{.Values.kratos.database.username}}:{{.Values.kratos.database.password}}@{{.Values.kratos.database.domain}}:{{.Values.kratos.database.port}}/{{.Values.kratos.database.loginDatabase}}?sslmode=allow
  Kratos-COURIER_SMTP_CONNECTION_URI: smtps://{{.Values.kratos.smtps.username}}:{{.Values.kratos.smtps.password}}@{{.Values.kratos.smtps.domain}}:{{.Values.kratos.smtps.port}}/?skip_ssl_verify=true&legacy_ssl=true
