apiVersion: v1
kind: Service
metadata:
  name: fnfcentral
  labels:
    app: fnfcentral
spec:
  selector:
    app: fnfcentral
  ports:
    - name: fnfcentral-http
      protocol: TCP
      port: 80
      targetPort: 3000
