fnfcentral:
  scale: 3
  image: "dualvs/fnfcentral"
  tag: "canary"
  domain: "canary.fnfcentral.com"
  sslMode: "self"
  database:
    username: "postgres"
    password: "password"
    domain: "sqldb"
    port: "5432"
    loginDatabase: "postgres"
  kratos:
    url: "kratos:4433"
  ldap:
    url: "ldap://ldap:389"
    bind:
      dn: "cn=admin,dc=fnfcentral,dc=com"
      pass: "admin_pass"
    search:
      base: "dc=fnfcentral,dc=com"
      filter: "(cn={{username}})"
  jwt:
    secret: "superSecretSecret"
kratos:
  scale: 3
  image: "dualvs/fnfcentral-kratos"
  tag: "canary"
  domain: "user.canary.fnfcentral.com"
  sslMode: "self"
  database:
    username: "postgres"
    password: "password"
    domain: "sqldb"
    port: "5432"
    loginDatabase: "postgres"
  smtps:
    username: "username"
    password: "password"
    domain: "smtp"
    port: "1025"
  email:
    name: "no-reply"
    domain: "canary.fnfcentral.com"
